version: "3.9"
services:
  api:
    image: inventory-app
    container_name: inventory-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/inventory
    depends_on:
      - mongo
    volumes:
      - ./public/uploads:/app/public/uploads

  mongo:
    image: mongo:7
    container_name: inventory-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
